config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :centros

  resources :poblacions

  resources :usuarios

  resources :centro_usuarios

  resources :dispositivos

  resources :ios

  resources :tetras

  resources :operador_virtuals

  resources :log_operador_virtuals

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/anotacion.rb
class Anotacion < ActiveRecord::Base
  belongs_to :emergencia
  belongs_to :user
end

app/models/centro.rb
class Centro < ActiveRecord::Base
end

app/models/centro_activado.rb
class CentroActivado < ActiveRecord::Base
  belongs_to :emergencia
end

app/models/centro_usuario.rb
class CentroUsuario < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :centro
end

app/models/dano.rb
class Dano < ActiveRecord::Base
  belongs_to :emergencia
end

app/models/dispositivo.rb
class Dispositivo < ActiveRecord::Base
  belongs_to :usuario
  has_one :ios
  has_one :tetra
end

app/models/emergencia.rb
class Emergencia < ActiveRecord::Base
end

app/models/io.rb
class Io < ActiveRecord::Base
  belongs_to :dispositivo
end

app/models/ios.rb
class Ios < ActiveRecord::Base
  belongs_to :dispositivo
end

app/models/operador_virtual.rb
class OperadorVirtual < ActiveRecord::Base
  belongs_to :user
end

app/models/poblacion.rb
class Poblacion < ActiveRecord::Base
  belongs_to :centro
end

app/models/seguimiento.rb
class Seguimiento < ActiveRecord::Base
  belongs_to :emergencia
  belongs_to :dispositivo
end

app/models/tetra.rb
class Tetra < ActiveRecord::Base
  belongs_to :dispositivo
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :user
end

app/controllers/operador_virtuals_controller.rb
class OperadorVirtualsController < ApplicationController
  before_action :set_operador_virtual, only: [:show, :edit, :update, :destroy]

  # GET /operador_virtuals
  # GET /operador_virtuals.json
  def index
    @operador_virtuals = OperadorVirtual.all
  end

  # GET /operador_virtuals/1
  # GET /operador_virtuals/1.json
  def show
  end

  # GET /operador_virtuals/new
  def new
    @operador_virtual = OperadorVirtual.new
  end

  # GET /operador_virtuals/1/edit
  def edit
  end

  # POST /operador_virtuals
  # POST /operador_virtuals.json
  def create
    @operador_virtual = OperadorVirtual.new(operador_virtual_params)

    respond_to do |format|
      if @operador_virtual.save
        format.html { redirect_to @operador_virtual, notice: 'Operador virtual was successfully created.' }
        format.json { render :show, status: :created, location: @operador_virtual }
      else
        format.html { render :new }
        format.json { render json: @operador_virtual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operador_virtuals/1
  # PATCH/PUT /operador_virtuals/1.json
  def update
    respond_to do |format|
      if @operador_virtual.update(operador_virtual_params)
        format.html { redirect_to @operador_virtual, notice: 'Operador virtual was successfully updated.' }
        format.json { render :show, status: :ok, location: @operador_virtual }
      else
        format.html { render :edit }
        format.json { render json: @operador_virtual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operador_virtuals/1
  # DELETE /operador_virtuals/1.json
  def destroy
    @operador_virtual.destroy
    respond_to do |format|
      format.html { redirect_to operador_virtuals_url, notice: 'Operador virtual was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operador_virtual
      @operador_virtual = OperadorVirtual.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operador_virtual_params
      params.require(:operador_virtual).permit(:user_id, :descripcion)
    end
end

app/helpers/centros_helper.rb
module CentrosHelper
end

app/helpers/ios_helper.rb
module IosHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/operador_virtuals_helper.rb
module OperadorVirtualsHelper
end

app/helpers/poblacions_helper.rb
module PoblacionsHelper
end

app/helpers/tetras_helper.rb
module TetrasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/operador_virtuals/_form.html.erb
<%= form_for @operador_virtual, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :descripcion, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :descripcion, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  operador_virtuals_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/operador_virtuals/edit.html.erb
<%- model_class = OperadorVirtual -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => OperadorVirtual %></h1>
</div>
<%= render :partial => 'form' %>

app/views/operador_virtuals/index.html.erb
<%- model_class = OperadorVirtual -%>
<div class="page-header">
  <h1><%=t '.title', :default => OperadorVirtual %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @operador_virtuals.each do |operador_virtual| %>
      <tr>
        <td><%= operador_virtual.id %></td>
        <td><%= operador_virtual.descripcion %></td>
        <td><%=l operador_virtual.created_at, format: :long %></td>
        <td>
          <%= link_to operador_virtual_path(operador_virtual), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to operador_virtual_path(operador_virtual), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_operador_virtual_path,
            :class => 'btn btn-primary' %>

app/views/operador_virtuals/new.html.erb
<%- model_class = OperadorVirtual -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => OperadorVirtual %></h1>
</div>
<%= render :partial => 'form' %>

app/views/operador_virtuals/show.html.erb
<%- model_class = OperadorVirtual -%>
<div class="page-header">
  <h1><%=t '.title', :default => OperadorVirtual %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:descripcion) %></dt>
      <dd><pre class="prettyprint"><%= @operador_virtual.descripcion %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              operador_virtuals_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_operador_virtual_path(@operador_virtual), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              operador_virtual_path(@operador_virtual),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>